### PR TITLE
Add proper Windows support

### LINKED ISSUE #29: Make CLI client work on Windows
The blocker for this was this lanterna issue:
https://github.com/mabe02/lanterna/issues/422

But it seems like it's been addressed (at least partially?). It's a matter of trying it on Windows and seeing what happens.

### PR DESCRIPTION
**Pull request by reibitto**
Closes #29

I finally tried Command Center on a Windows machine and a bunch of things weren't working the way they were supposed to. This fixes everything I found. Both the cli-client and daemon should work properly now.

### CODE REVIEW

**Comment by sne11ius** [comment]
Hey. I started a similar project (https://github.com/sne11ius/batarang) - mainly just to try and use new tech.
I managed to create a github action for creatting native executables via graalvm. The linux-version actually works fine, too ;)
I understand you have a working windows build? Did you also try to create a native image via graalvm for windows? If so ... did it work?

**Comment by reibitto** [comment]
No, unfortunately the native image build for this project on Windows doesn't work yet. 😟 I believe the issue comes from lanterna and how the Windows terminal requires JNA.

I haven't investigated how to get JNA + native-image working together, but it sounds like it would be difficult and support for it isn't planned.

Maybe it would be better to come at it from the other direction and remove the JNA dependency from lanterna itself. I think only 1 or 2 classes use JNA. Maybe JNI plays better with native-image. That would be something worth looking into I think.

**Comment by reibitto** [comment]
Actually, it's weird. At one point is was working. Maybe I'm mistaken on what the issue actually is. I might need to create a small sample project and check again.

**Comment by reibitto** [comment]
Alright, sorry, I think I remember now. So this PR adds Windows support and that works with a normal JVM. Before this PR even that didn't work. But I'm pretty sure a native-image build for Windows never worked. That would make sense. So yeah, I'm pretty sure JNA is the cause.

**Comment by sne11ius** [comment]
Ah thanks. I think I am like 80%ish of the way there. But jna & graalvm native image seem to really not work together well.
The last 20% are going to be tough I guess ;) - Not sure if I'm willing to put myself through this...
Anyway, thank you. I'll let you know if I ever happen to make it work.

**Pull request merged**
