### PR TITLE
Add command to search Maven

### PR DESCRIPTION
**Pull request by tuleism**
Ref #15

It send a request to https://search.maven.org/ and parse the result. Here are some examples:

Screenshot 2020-07-29 at 18 59 38

Screenshot 2020-07-29 at 19 00 23

### CODE REVIEW

**Comment by tuleism** [comment]
>Like if you use the argsPreview(args: List[String], context: CommandContext) event you could also specify it in CLI-like format like -g group -a artifact and so on. The benefit there being that you can better error messages and usage hints with Decline.

Let me add that.

>I wonder if it's worth accepting SBT-like format too like: "dev.zio" %% "zio" (leaving off the version) and "dev.zio" %% "zio" % "1.0.0-RC21-2". Though supporting %% is a little awkward since we don't really know which version of Scala they're using.

Maybe we can allow user to configure the scala version?

**Comment by reibitto** [comment]
Thanks. I wonder if this means 2 HTTP requests will be sent. I guess it depends if you early-exit `prefixPreview` case if it finds it in the other format. But doing so right now might be a little tricky. I think I might need to tweak the execution model to make this easier. Such as maybe having only 1 event handler and an ADT for the different cases? I don't know yet, but it's something that needs more thought. I think that might simplify a lot of things.

> Maybe we can allow user to configure the scala version?

That could work. Or just assume the latest Scala version. I don't think it's _too_ bad if not accurate 100% of the time. If they want something other than the latest, the option to use `%` instead of `%%` is always there.

**Comment by tuleism** [comment]
>Thanks. I wonder if this means 2 HTTP requests will be sent. I guess it depends if you early-exit prefixPreview case if it finds it in the other format. But doing so right now might be a little tricky. I think I might need to tweak the execution model to make this easier. Such as maybe having only 1 event handler and an ADT for the different cases? I don't know yet, but it's something that needs more thought. I think that might simplify a lot of things.

Make sense, I overlooked that. Will leave the args one for later then.

>That could work. Or just assume the latest Scala version. I don't think it's too bad if not accurate 100% of the time. If they want something other than the latest, the option to use % instead of %% is always there.

👍

**Comment by tuleism** [comment]
@reibitto see if this is good to merge. I think it's better to add the `%%` feature once we have some testing in place (#38).

**Comment by reibitto** [comment]
Sure, that's fine with me.

**Comment by reibitto** [comment]
The new execution model should solve the double execution problem. I have an example in `SearchUrlCommand` for how it can be addressed. There's 1 preview method and then I do `prefixPreview.orElse(rawInputPreview)` to support both modes.

As for adding tests, I'll probably do that over the weekend.

**Pull request merged**
